## Pandas is powerful library used for data manupulating widly used for data analytic

## Series

In [8]:
import pandas as pd

# only performs columns 
data = [1,2,3,4,5]
series =pd.Series(data)
print(series)

dic = {"one":1 , "two":2 , "three" :3}
print(pd.Series(dic))

0    1
1    2
2    3
3    4
4    5
dtype: int64
one      1
two      2
three    3
dtype: int64

## Data Frames

In [ ]:
# performs rows and columns
data ={
    "name":["ram" ,"thiru", 'gowri'],
    "age":[17,30,20],
    "voted":[1,2,3]
}
print(pd.DataFrame(data))

    name  age  voted
0    ram   17      1
1  thiru   30      2
2  gowri   20      3

## Data manupulation:

## reading various source Using pandas

In [1]:

# using to load the data in diffrent files and manupulate to it

# convertion of json -> data format

import pandas as pd
import json

data1 = '[{"name":"sathish","email":"sathish@gmail.com","roll":"ML"}]'

data = json.loads(data1)
df = pd.DataFrame(data)

df

      name              email roll
0  sathish  sathish@gmail.com   ML

In [ ]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

## xlsFile

In [25]:
df1=pd.read_excel("Sathish_LinkedIn_Job_Matches_Bangalore.xlsx")
df1

,"Sathish Kumar S — LinkedIn Job Match Report | Bangalore | May 28, 2026",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Resume: Java | Spring Boot | MySQL | REST APIs...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,#,Job Title,Company,Location (Bangalore),Work Mode,Experience Required,Match Score (%),Match Level,Matched Skills,Skill Gaps,Salary Range (LPA),LinkedIn URL,Posted,Application Priority
3,1,Junior Java Developer,triSys,Bengaluru (Koramangala),On-site,0-1 year (Fresher OK),92,Excellent,"Java, Spring Boot, REST APIs, SQL, MySQL, Git,...",Node.js (nice-to-have),3.0-5.0,https://in.linkedin.com/jobs/view/java-develop...,Today,Apply Now - Top Match
4,2,Associate Software Engineer - Java,Infosys,Bengaluru (Electronic City),On-site,Fresher (2026 Batch),88,Excellent,"Java, OOP, SQL, Collections, Git, Problem Solving","Microservices, Docker, Kafka",3.5-4.5,https://www.linkedin.com/company/infosys/jobs/,Today,Apply Now - Top Match
5,3,Software Engineer Trainee - Java Backend,Wipro,Bengaluru (Sarjapur Road),Hybrid,Fresher / 0-1 year,85,Excellent,"Java, JDBC, MySQL, HTML, CSS, JavaScript, REST...","Kubernetes, CI/CD, Cloud",3.0-4.0,https://www.linkedin.com/company/wipro/jobs/,Today,Apply Now - Top Match
6,4,Java Developer Fresher,HireWand,Bengaluru (Indiranagar),On-site,Fresher - 0 years,87,Excellent,"Core Java, SQL, OOP, Problem Solving, Backend Dev","Node.js (secondary, trainable)",2.5-4.0,https://in.linkedin.com/jobs/view/java-develop...,Today,Apply Now - Top Match
7,5,Software Engineer - Full Stack (Java+JS),LTIMindtree,Bengaluru (Whitefield),On-site,0-2 years,82,Strong,"Java, JavaScript, HTML5, CSS3, MySQL, REST API...","React.js, Microservices, Docker",3.5-6.0,https://www.linkedin.com/company/ltimindtree/j...,Today,Highly Recommended
8,6,Junior Backend Developer - Java,Capgemini,Bengaluru (Manyata Tech Park),Hybrid,Fresher / 0-1 year,80,Strong,"Java, Spring Boot, REST APIs, MySQL, JDBC, Hib...","Cloud, CI/CD, Agile tools (Jira)",3.5-5.5,https://www.linkedin.com/company/capgemini/jobs/,Today,Highly Recommended
9,7,Graduate Trainee - Java Developer,Cognizant,Bengaluru (Bellandur),On-site,Fresher (2025/2026 Batch),79,Strong,"Core Java, SQL, OOP, Collections, Git, HTML/CSS","Spring (deep), Microservices, Scrum",3.0-4.5,https://www.linkedin.com/company/cognizant/jobs/,Today,Highly Recommended
10,8,Java Backend Engineer (Entry Level),Startup / Fintech,Bengaluru (HSR Layout),On-site,1 yr or strong fresher w/ projects,76,Good,"Java, Spring Boot, MySQL, REST APIs, JDBC, Git...","Kafka, Redis, Distributed Systems",4.0-7.0,https://www.linkedin.com/jobs/java-developer-j...,Today,Recommended
11,9,Software Developer - Java + Web,Tech Mahindra,Bengaluru (Outer Ring Road),On-site,0-2 years,74,Good,"Java, HTML5, CSS3, JavaScript, MySQL, Git, RES...","Angular/React, Microservices, CI/CD",3.0-5.0,https://www.linkedin.com/company/tech-mahindra...,Today,Recommended
12,10,Junior Full Stack Developer (Java/JS),Persistent Systems,Bengaluru (Marathahalli),Hybrid,0-2 years,71,Good,"Java, JavaScript, HTML, CSS, MySQL, REST APIs,...","React.js, Node.js, Docker, Cloud, GraphQL",3.5-6.0,https://www.linkedin.com/company/persistent-sy...,Today,Recommended

## pickle Format

In [ ]:
#code can taken in production using pickle format

#convert xls file to pickle file 

df.to_pickle("data_pickle")  # already created file can convert pickle file 

df2 =pd.read_pickle("data_pickle") #read that pickle file it show pickle file
df2

      name              email roll
0  sathish  sathish@gmail.com   ML

:

In [9]:
#age =[20,46,45,23,33]
age=["goms" , "siva" , "ram"]
ser=pd.Series(age,index = [99,98,97]) #modify the indexes
print(ser)
print(ser.loc[98]) #used for acess the value using indexes
print(ser.iloc[2])

99    goms
98    siva
97     ram
dtype: str
siva
ram

## Dictionary format

In [17]:
age={
    "goms":12,
    "shiva":45,
    "thiru":33
}
s=pd.Series(age)
print(s[s>20])

shiva    45
thiru    33
dtype: int64

## Data Frame

In [28]:
#create a dictnory it can contains set of series
students ={
    "name":["goms","shiva","rani"],
    "rollno":[1,2,3],
    "cgpa":[8.4,7.6,6.6]
}
#print(pd.DataFrame(students))

df=pd.DataFrame(students,index=[44,45,46])


# try to fix the new data frame column
df["medium"]=["english"," english","tamil"]


#try to fix neww data frame row

std=pd.DataFrame({"name":"raja","rollno":4,"cgpa":7.7 , "medium":"tamil"} , index=[47])
df =pd.concat([df,std])
print(df)

     name  rollno  cgpa    medium
44   goms       1   8.4   english
45  shiva       2   7.6   english
46   rani       3   6.6     tamil
47   raja       4   7.7     tamil

## Import Files

In [ ]:
import pandas as pd
df = pd.read_excel("Sathish_LinkedIn_Job_Matches_Bangalore.xlsx")
#print(df.head()) #df.head() using 1sr=t 5 coustomer datails show
print(df.to_string())

       #                                 Job Title             Company           Location (Bangalore) Location (Bangalore).1              Location (Bangalore).2  Location (Bangalore).3 Location (Bangalore).4                                             Location (Bangalore).5                     Location (Bangalore).6 Location (Bangalore).7                                                           Location (Bangalore).8 Location (Bangalore).9 Location (Bangalore).10
0    NaN                                       NaN                 NaN                            NaN                    NaN                                 NaN                     NaN                    NaN                                                                NaN                                        NaN                    NaN                                                                              NaN                    NaN                     NaN
1    1.0                     Junior Java Developer              triSys        Bengaluru (Koramangala)                On-site               0-1 year (Fresher OK)                    92.0              Excellent                 Java, Spring Boot, REST APIs, SQL, MySQL, Git, OOP                     Node.js (nice-to-have)                3.0-5.0  https://in.linkedin.com/jobs/view/java-developer-fresher-at-hirewand-3330590765                  Today   Apply Now - Top Match
2    2.0        Associate Software Engineer - Java             Infosys    Bengaluru (Electronic City)                On-site                Fresher (2026 Batch)                    88.0              Excellent                  Java, OOP, SQL, Collections, Git, Problem Solving               Microservices, Docker, Kafka                3.5-4.5                                   https://www.linkedin.com/company/infosys/jobs/                  Today   Apply Now - Top Match
3    3.0  Software Engineer Trainee - Java Backend               Wipro      Bengaluru (Sarjapur Road)                 Hybrid                  Fresher / 0-1 year                    85.0              Excellent           Java, JDBC, MySQL, HTML, CSS, JavaScript, REST APIs, Git                   Kubernetes, CI/CD, Cloud                3.0-4.0                                     https://www.linkedin.com/company/wipro/jobs/                  Today   Apply Now - Top Match
4    4.0                    Java Developer Fresher            HireWand        Bengaluru (Indiranagar)                On-site                   Fresher - 0 years                    87.0              Excellent                  Core Java, SQL, OOP, Problem Solving, Backend Dev             Node.js (secondary, trainable)                2.5-4.0  https://in.linkedin.com/jobs/view/java-developer-fresher-at-hirewand-3330590765                  Today   Apply Now - Top Match
5    5.0  Software Engineer - Full Stack (Java+JS)         LTIMindtree         Bengaluru (Whitefield)                On-site                           0-2 years                    82.0                 Strong  Java, JavaScript, HTML5, CSS3, MySQL, REST APIs, Spring Boot, Git            React.js, Microservices, Docker                3.5-6.0                               https://www.linkedin.com/company/ltimindtree/jobs/                  Today      Highly Recommended
6    6.0           Junior Backend Developer - Java           Capgemini  Bengaluru (Manyata Tech Park)                 Hybrid                  Fresher / 0-1 year                    80.0                 Strong       Java, Spring Boot, REST APIs, MySQL, JDBC, Hibernate (Basic)           Cloud, CI/CD, Agile tools (Jira)                3.5-5.5                                 https://www.linkedin.com/company/capgemini/jobs/                  Today      Highly Recommended
7    7.0         Graduate Trainee - Java Developer           Cognizant          Bengaluru (Bellandur)                On-site           Fresher (2025/2026 Batch)                    79.0                 Strong                    Core Java, SQL, OOP, Collections, Git, HTML/CSS        Spring (deep), Microservices, Scrum                3.0-4.5                                 https://www.linkedin.com/company/cognizant/jobs/                  Today      Highly Recommended
8    8.0       Java Backend Engineer (Entry Level)   Startup / Fintech         Bengaluru (HSR Layout)                On-site  1 yr or strong fresher w/ projects                    76.0                   Good            Java, Spring Boot, MySQL, REST APIs, JDBC, Git, ACID TX          Kafka, Redis, Distributed Systems                4.0-7.0                      https://www.linkedin.com/jobs/java-developer-jobs-bengaluru                  Today             Recommended
9    9.0           Software Developer - Java + Web       Tech Mahindra    Bengaluru (Outer Ring Road)                On-site                           0-2 years                    74.0                   Good               Java, HTML5, CSS3, JavaScript, MySQL, Git, REST APIs        Angular/React, Microservices, CI/CD                3.0-5.0                             https://www.linkedin.com/company/tech-mahindra/jobs/                  Today             Recommended
10  10.0     Junior Full Stack Developer (Java/JS)  Persistent Systems       Bengaluru (Marathahalli)                 Hybrid                           0-2 years                    71.0                   Good         Java, JavaScript, HTML, CSS, MySQL, REST APIs, Spring Boot  React.js, Node.js, Docker, Cloud, GraphQL                3.5-6.0                        https://www.linkedin.com/company/persistent-systems/jobs/                  Today             Recommended

## Selection

In [ ]:
print(df[['Job Title','Company','#']].to_string())  # select specific column

                                   Job Title             Company     #
0                                        NaN                 NaN   NaN
1                      Junior Java Developer              triSys   1.0
2         Associate Software Engineer - Java             Infosys   2.0
3   Software Engineer Trainee - Java Backend               Wipro   3.0
4                     Java Developer Fresher            HireWand   4.0
5   Software Engineer - Full Stack (Java+JS)         LTIMindtree   5.0
6            Junior Backend Developer - Java           Capgemini   6.0
7          Graduate Trainee - Java Developer           Cognizant   7.0
8        Java Backend Engineer (Entry Level)   Startup / Fintech   8.0
9            Software Developer - Java + Web       Tech Mahindra   9.0
10     Junior Full Stack Developer (Java/JS)  Persistent Systems  10.0

In [49]:
#specific row
#print(df.loc[1])
df = pd.read_excel("Sathish_LinkedIn_Job_Matches_Bangalore.xlsx" ,index_col="#")
df.to_string()
#print(df.loc[6.0,["Job Title" , "Company"]])  #specific column of specific rows
#print(df.loc[6.0 : 10.0,["Job Title" , "Company"]])  # ranges
print(df.iloc[0:5:1 , 1:3])  #rows , columns ,steps

      Company         Location (Bangalore)
#
NaN       NaN                          NaN
1.0    triSys      Bengaluru (Koramangala)
2.0   Infosys  Bengaluru (Electronic City)
3.0     Wipro    Bengaluru (Sarjapur Road)
4.0  HireWand      Bengaluru (Indiranagar)

## Filtering

In [ ]:
#filtered = df[df['Location (Bangalore).3']>=80.0]  #single conndition
filtered = df[(df['Location (Bangalore).4']=="Strong") & (df['Location (Bangalore).3']>=80.0)] # multiple condition also satisified

print(filtered.to_string())

                                    Job Title      Company           Location (Bangalore) Location (Bangalore).1 Location (Bangalore).2  Location (Bangalore).3 Location (Bangalore).4                                             Location (Bangalore).5            Location (Bangalore).6 Location (Bangalore).7                              Location (Bangalore).8 Location (Bangalore).9 Location (Bangalore).10
#
5.0  Software Engineer - Full Stack (Java+JS)  LTIMindtree         Bengaluru (Whitefield)                On-site              0-2 years                    82.0                 Strong  Java, JavaScript, HTML5, CSS3, MySQL, REST APIs, Spring Boot, Git   React.js, Microservices, Docker                3.5-6.0  https://www.linkedin.com/company/ltimindtree/jobs/                  Today      Highly Recommended
6.0           Junior Backend Developer - Java    Capgemini  Bengaluru (Manyata Tech Park)                 Hybrid     Fresher / 0-1 year                    80.0                 Strong       Java, Spring Boot, REST APIs, MySQL, JDBC, Hibernate (Basic)  Cloud, CI/CD, Agile tools (Jira)                3.5-5.5    https://www.linkedin.com/company/capgemini/jobs/                  Today      Highly Recommended

## Aggregate function

In [2]:
df = pd.read_excel("Sathish_LinkedIn_Job_Matches_Bangalore.xlsx" ,index_col="#")
df.to_string()
print(df.mean(numeric_only=True))
print(df.max(numeric_only=True))
print(df.sum(numeric_only=True))
print(df.count(numeric_only=True))
print(df.min(numeric_only=True))
print(df.median(numeric_only=True))
#print(df.mode(numeric_only=True))

Location (Bangalore).3    81.4
dtype: float64
Location (Bangalore).3    92.0
dtype: float64
Location (Bangalore).3    814.0
dtype: float64
Location (Bangalore).3    10
dtype: int64
Location (Bangalore).3    71.0
dtype: float64
Location (Bangalore).3    81.0
dtype: float64

## Data Cleaning

In [ ]:

import pandas as pd
df=pd.read_excel("Sathish_LinkedIn_Job_Matches_Bangalore.xlsx" , index_col="#")
df=df.drop(columns=["Job Title"])  # drop the column
print(df.to_string()) 
# df.dropna()
#df.fillna()
#df["verity"]=df["verity"].replace()
#df["verity"]=df["veritey"].str.lower()
#df["verity"]=df["verity"].astype(np.int64)
#df=df.drop_duplicates()

                 Company           Location (Bangalore) Location (Bangalore).1              Location (Bangalore).2  Location (Bangalore).3 Location (Bangalore).4                                             Location (Bangalore).5                     Location (Bangalore).6 Location (Bangalore).7                                                           Location (Bangalore).8 Location (Bangalore).9 Location (Bangalore).10
#
NaN                  NaN                            NaN                    NaN                                 NaN                     NaN                    NaN                                                                NaN                                        NaN                    NaN                                                                              NaN                    NaN                     NaN
1.0               triSys        Bengaluru (Koramangala)                On-site               0-1 year (Fresher OK)                    92.0              Excellent                 Java, Spring Boot, REST APIs, SQL, MySQL, Git, OOP                     Node.js (nice-to-have)                3.0-5.0  https://in.linkedin.com/jobs/view/java-developer-fresher-at-hirewand-3330590765                  Today   Apply Now - Top Match
2.0              Infosys    Bengaluru (Electronic City)                On-site                Fresher (2026 Batch)                    88.0              Excellent                  Java, OOP, SQL, Collections, Git, Problem Solving               Microservices, Docker, Kafka                3.5-4.5                                   https://www.linkedin.com/company/infosys/jobs/                  Today   Apply Now - Top Match
3.0                Wipro      Bengaluru (Sarjapur Road)                 Hybrid                  Fresher / 0-1 year                    85.0              Excellent           Java, JDBC, MySQL, HTML, CSS, JavaScript, REST APIs, Git                   Kubernetes, CI/CD, Cloud                3.0-4.0                                     https://www.linkedin.com/company/wipro/jobs/                  Today   Apply Now - Top Match
4.0             HireWand        Bengaluru (Indiranagar)                On-site                   Fresher - 0 years                    87.0              Excellent                  Core Java, SQL, OOP, Problem Solving, Backend Dev             Node.js (secondary, trainable)                2.5-4.0  https://in.linkedin.com/jobs/view/java-developer-fresher-at-hirewand-3330590765                  Today   Apply Now - Top Match
5.0          LTIMindtree         Bengaluru (Whitefield)                On-site                           0-2 years                    82.0                 Strong  Java, JavaScript, HTML5, CSS3, MySQL, REST APIs, Spring Boot, Git            React.js, Microservices, Docker                3.5-6.0                               https://www.linkedin.com/company/ltimindtree/jobs/                  Today      Highly Recommended
6.0            Capgemini  Bengaluru (Manyata Tech Park)                 Hybrid                  Fresher / 0-1 year                    80.0                 Strong       Java, Spring Boot, REST APIs, MySQL, JDBC, Hibernate (Basic)           Cloud, CI/CD, Agile tools (Jira)                3.5-5.5                                 https://www.linkedin.com/company/capgemini/jobs/                  Today      Highly Recommended
7.0            Cognizant          Bengaluru (Bellandur)                On-site           Fresher (2025/2026 Batch)                    79.0                 Strong                    Core Java, SQL, OOP, Collections, Git, HTML/CSS        Spring (deep), Microservices, Scrum                3.0-4.5                                 https://www.linkedin.com/company/cognizant/jobs/                  Today      Highly Recommended
8.0    Startup / Fintech         Bengaluru (HSR Layout)                On-site  1 yr or strong fresher w/ projects                    76.0                   Good            Java, Spring Boot, MySQL, REST APIs, JDBC, Git, ACID TX          Kafka, Redis, Distributed Systems                4.0-7.0                      https://www.linkedin.com/jobs/java-developer-jobs-bengaluru                  Today             Recommended
9.0        Tech Mahindra    Bengaluru (Outer Ring Road)                On-site                           0-2 years                    74.0                   Good               Java, HTML5, CSS3, JavaScript, MySQL, Git, REST APIs        Angular/React, Microservices, CI/CD                3.0-5.0                             https://www.linkedin.com/company/tech-mahindra/jobs/                  Today             Recommended
10.0  Persistent Systems       Bengaluru (Marathahalli)                 Hybrid                           0-2 years                    71.0                   Good         Java, JavaScript, HTML, CSS, MySQL, REST APIs, Spring Boot  React.js, Node.js, Docker, Cloud, GraphQL                3.5-6.0                        https://www.linkedin.com/company/persistent-systems/jobs/                  Today             Recommended